/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-10-28 17:08:27 UTC)
 * on 2014-10-30 at 03:35:21 UTC 
 * Modify at your own risk.
 */

package com.huertapp.model.gardenAPI.model;

/**
 * Model definition for Garden.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gardenAPI. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Garden extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean directLight;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float length;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer lightHoursADay;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean outerGarden;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float width;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDirectLight() {
    return directLight;
  }

  /**
   * @param directLight directLight or {@code null} for none
   */
  public Garden setDirectLight(java.lang.Boolean directLight) {
    this.directLight = directLight;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Garden setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLength() {
    return length;
  }

  /**
   * @param length length or {@code null} for none
   */
  public Garden setLength(java.lang.Float length) {
    this.length = length;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLightHoursADay() {
    return lightHoursADay;
  }

  /**
   * @param lightHoursADay lightHoursADay or {@code null} for none
   */
  public Garden setLightHoursADay(java.lang.Integer lightHoursADay) {
    this.lightHoursADay = lightHoursADay;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Garden setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getOuterGarden() {
    return outerGarden;
  }

  /**
   * @param outerGarden outerGarden or {@code null} for none
   */
  public Garden setOuterGarden(java.lang.Boolean outerGarden) {
    this.outerGarden = outerGarden;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public Garden setType(java.lang.String type) {
    this.type = type;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getWidth() {
    return width;
  }

  /**
   * @param width width or {@code null} for none
   */
  public Garden setWidth(java.lang.Float width) {
    this.width = width;
    return this;
  }

  @Override
  public Garden set(String fieldName, Object value) {
    return (Garden) super.set(fieldName, value);
  }

  @Override
  public Garden clone() {
    return (Garden) super.clone();
  }

}
